name: release

on:
  push:
    tags:
      - release/v*
jobs:
  build-and-push:
    strategy:
      matrix:
        config:
          - { platform: linux, arch: amd64 }
          - { platform: linux, arch: arm64 }
    runs-on: ubuntu-latest
    steps:
      - name: '[preparation] checkout the current branch'
        uses: actions/checkout@v3.5.3
      - name: '[preparation] set up qemu'
        uses: docker/setup-qemu-action@v2
      - name: '[preparation] set up docker context for buildx'
        run: docker context create builders
      - name: '[preparation] set up docker buildx'
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
          #  like command: docker buildx create --use --name builders
      - name: '[preparation] docker login'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: '[preparation] get release version'
        id: get_version
        # refs/tags/release/v1.0 -> v1.0
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/*/}
      - name: '[execution] build and push docker images'
        run: |
          docker buildx build --output=type=registry --platform ${{ matrix.config.platform }}/${{ matrix.config.arch }} -t "${DOCKER_HUB_REPO}:${CONTAINER_IMAGE_TAG}" -f ./Dockerfile .
        env:
          DOCKER_HUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/danchoicloud
          CONTAINER_IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}

          docker buildx build --output=type=registry --platform linux/arm64 -t "hoangndst/danchoicloud:v0.1.0" -f ./Dockerfile .